from django.urls import path

from . import operations_views as views
from . import resource_views as resources


app_name = 'operations'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('bookings/', views.booking_list, name='booking_list'),
    path('bookings/export/', views.booking_export, name='booking_export'),
    path('bookings/<int:booking_id>/', views.booking_detail, name='booking_detail'),
    path('bookings/<int:booking_id>/details/', views.booking_update_details, name='booking_update_details'),
    path('bookings/<int:booking_id>/status/', views.booking_update_status, name='booking_update_status'),
    path('bookings/<int:booking_id>/payment/', views.booking_record_payment, name='booking_record_payment'),
    path('bookings/<int:booking_id>/pickup/', views.booking_pickup, name='booking_pickup'),
    path('bookings/<int:booking_id>/welcome-package/', views.booking_welcome_package, name='booking_welcome_package'),
    path('tours/', views.tour_list, name='tour_list'),
    path('tours/<int:tour_id>/', views.tour_detail, name='tour_detail'),
    path('customers/', views.customer_list, name='customer_list'),
    path('customers/<int:customer_id>/', views.customer_detail, name='customer_detail'),
    path('documents/', views.document_queue, name='document_queue'),
    path('pickups/', views.pickup_queue, name='pickup_queue'),
    path('providers/', views.provider_list, name='provider_list'),
    path('reports/', views.reports, name='reports'),
    path('resources/', resources.resource_dashboard, name='resource_dashboard'),
    path('employees/', resources.employee_list, name='employee_list'),
    path('employees/new/', resources.employee_form, name='employee_create'),
    path('employees/<int:employee_id>/edit/', resources.employee_form, name='employee_edit'),
    path('crew/', resources.crew_list, name='crew_list'),
    path('crew/<int:crew_id>/', resources.crew_detail, name='crew_detail'),
    path('crew/documents/<int:document_id>/review/', resources.crew_document_review, name='crew_document_review'),
    path('crew/qualifications/<int:qualification_id>/verify/', resources.crew_qualification_verify, name='crew_qualification_verify'),
    path('opportunities/', resources.opportunity_list, name='opportunity_list'),
    path('opportunities/new/', resources.opportunity_form, name='opportunity_create'),
    path('tours/<int:tour_id>/opportunities/new/', resources.opportunity_form, name='tour_opportunity_create'),
    path('opportunities/<int:opportunity_id>/', resources.opportunity_detail, name='opportunity_detail'),
    path('opportunities/<int:opportunity_id>/edit/', resources.opportunity_form, name='opportunity_edit'),
    path('applications/<int:application_id>/review/', resources.application_review, name='application_review'),
    path('applications/<int:application_id>/offer/', resources.offer_create, name='offer_create'),
    path('engagements/', resources.engagement_list, name='engagement_list'),
    path('engagements/new/', resources.engagement_form, name='engagement_create'),
    path('tours/<int:tour_id>/engagements/new/', resources.engagement_form, name='tour_engagement_create'),
    path('engagements/<int:engagement_id>/', resources.engagement_detail, name='engagement_detail'),
    path('engagements/<int:engagement_id>/edit/', resources.engagement_form, name='engagement_edit'),
    path('engagements/<int:engagement_id>/status/', resources.engagement_status, name='engagement_status'),
    path('engagements/<int:engagement_id>/payment/', resources.engagement_payment, name='engagement_payment'),
    path('engagements/<int:engagement_id>/review/', resources.engagement_review, name='engagement_review'),
    path('training/', resources.training_list, name='training_list'),
    path('training/new/', resources.training_course_form, name='training_create'),
    path('training/<int:course_id>/edit/', resources.training_course_form, name='training_edit'),
    path('training/records/new/', resources.training_record_form, name='training_record_create'),
    path('crew/<int:crew_id>/training/new/', resources.training_record_form, name='crew_training_record_create'),
    path('training/records/<int:record_id>/edit/', resources.training_record_form, name='training_record_edit'),
    path('cases/', resources.case_list, name='case_list'),
    path('cases/<int:case_id>/', resources.case_detail, name='case_detail'),
    path('suppliers/', resources.supplier_list, name='supplier_list'),
    path('suppliers/new/', resources.supplier_form, name='supplier_create'),
    path('suppliers/<int:supplier_id>/', resources.supplier_detail, name='supplier_detail'),
    path('suppliers/<int:supplier_id>/edit/', resources.supplier_form, name='supplier_edit'),
    path('suppliers/<int:supplier_id>/services/new/', resources.supplier_service_form, name='supplier_service_create'),
    path('suppliers/<int:supplier_id>/assets/new/', resources.supplier_asset_form, name='supplier_asset_create'),
    path('suppliers/<int:supplier_id>/documents/new/', resources.supplier_document_form, name='supplier_document_create'),
    path('suppliers/documents/<int:document_id>/verify/', resources.supplier_document_verify, name='supplier_document_verify'),
    path('suppliers/<int:supplier_id>/contracts/new/', resources.supplier_contract_form, name='supplier_contract_create'),
    path('contracts/<int:contract_id>/rates/new/', resources.supplier_rate_form, name='supplier_rate_create'),
    path('tours/<int:tour_id>/resources/', resources.tour_resources, name='tour_resources'),
    path('tours/<int:tour_id>/requirements/new/', resources.requirement_form, name='requirement_create'),
    path('tours/<int:tour_id>/requirements/<int:requirement_id>/edit/', resources.requirement_form, name='requirement_edit'),
    path('requirements/<int:requirement_id>/rfq/', resources.rfq_form, name='rfq_create'),
    path('rfqs/', resources.rfq_list, name='rfq_list'),
    path('rfqs/<int:rfq_id>/', resources.rfq_detail, name='rfq_detail'),
    path('quotes/<int:quote_id>/select/', resources.quote_select, name='quote_select'),
    path('service-orders/', resources.service_order_list, name='service_order_list'),
    path('service-orders/<int:order_id>/', resources.service_order_detail, name='service_order_detail'),
    path('service-orders/<int:order_id>/status/', resources.service_order_status, name='service_order_status'),
    path('service-orders/<int:order_id>/review/', resources.supplier_review, name='supplier_review'),
    path('invoices/<int:invoice_id>/review/', resources.invoice_review, name='invoice_review'),
]
