# Generated by Django 5.2.3 on 2026-08-29 10:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_seed_website_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('country_of_origin', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adults', models.PositiveSmallIntegerField(default=1)),
                ('children', models.PositiveSmallIntegerField(default=0)),
                ('budget_tier', models.CharField(choices=[('economy', 'Economy'), ('comfort', 'Comfort'), ('premium', 'Premium'), ('luxury', 'Luxury'), ('flexible', 'Flexible / advise me')], default='flexible', max_length=20)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pace', models.CharField(choices=[('relaxed', 'Relaxed'), ('balanced', 'Balanced'), ('active', 'Active')], default='balanced', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('proposal_sent', 'Proposal sent'), ('changes_requested', 'Changes requested'), ('approved', 'Approved'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=30)),
                ('assigned_expert_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('booking_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom trip request',
                'verbose_name_plural': 'Custom trip requests',
                'ordering': ('-submitted_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='TripPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.JSONField(blank=True, default=list)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('guesthouse', 'Guesthouse'), ('homestay', 'Homestay'), ('mixed', 'A suitable mix'), ('advise', 'Advise me')], default='advise', max_length=20)),
                ('transport_preference', models.CharField(choices=[('private', 'Private vehicle'), ('shared', 'Shared transport'), ('flight', 'Domestic flight where practical'), ('mixed', 'Best practical mix'), ('advise', 'Advise me')], default='advise', max_length=20)),
                ('needs_local_guide', models.BooleanField(default=True)),
                ('needs_translator', models.BooleanField(default=False)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='home.triprequest')),
            ],
        ),
        migrations.CreateModel(
            name='RouteProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('proposed_entry_point', models.CharField(max_length=150)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('AFN', 'AFN'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('customer_message', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to traveller'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='draft', max_length=20)),
                ('booking_tour_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='home.triprequest')),
            ],
            options={
                'ordering': ('-version', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='EntryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_mode', models.CharField(choices=[('self', 'I will choose my entry point'), ('recommend', 'Recommend the best entry point'), ('flexible', 'Air or land — choose for me')], default='recommend', max_length=20)),
                ('transport_mode', models.CharField(choices=[('air', 'Air'), ('land', 'Land'), ('either', 'Either / advise me')], default='either', max_length=20)),
                ('arrival_origin', models.CharField(help_text='Country or city the traveller expects to arrive from.', max_length=150)),
                ('selected_entry_point', models.CharField(blank=True, choices=[('', 'Select an entry point'), ('kabul_airport', 'Kabul International Airport'), ('herat_airport', 'Herat International Airport'), ('mazar_airport', 'Mazar-i-Sharif Airport'), ('kandahar_airport', 'Kandahar Airport'), ('torkham_border', 'Torkham Border (Pakistan)'), ('spin_boldak', 'Spin Boldak (Pakistan)'), ('islam_qala', 'Islam Qala (Iran)'), ('hairatan', 'Hairatan (Uzbekistan)'), ('torghundi', 'Torghundi (Turkmenistan)'), ('other', 'Other')], max_length=50)),
                ('other_entry_point', models.CharField(blank=True, max_length=150)),
                ('recommended_entry_point', models.CharField(blank=True, max_length=150)),
                ('alternatives', models.TextField(blank=True)),
                ('operator_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Needs review'), ('recommended', 'Recommendation prepared'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('confirmed_by_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry_plan', to='home.triprequest')),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('nights', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_stops', to='home.popularplace')),
                ('trip_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='home.triprequest')),
            ],
            options={
                'ordering': ('position', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RouteProposalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('overnight_location', models.CharField(blank=True, max_length=150)),
                ('transport', models.CharField(blank=True, max_length=150)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.popularplace')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='home.routeproposal')),
            ],
            options={
                'ordering': ('day_number', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('proposal', 'day_number'), name='home_proposalday_unique_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='routeproposal',
            constraint=models.UniqueConstraint(fields=('trip_request', 'version'), name='home_routeproposal_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip_request', 'position'), name='home_tripstop_unique_position'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip_request', 'destination'), name='home_tripstop_unique_destination'),
        ),
    ]
