# Generated by Django 5.1.4 on 2026-08-29 18:30

import django.core.validators
import home.models
import home.validators
from django.db import migrations, models


LEGACY_PUBLIC_EMAILS = {"info@afghanawaits.com"}
PLACEHOLDER_PHONE_DIGITS = {"93123456789"}


def _usable_legacy_email(value):
    candidate = (value or "").strip().lower()
    return (
        candidate
        and "@" in candidate
        and candidate not in LEGACY_PUBLIC_EMAILS
        and not candidate.endswith(("@example.com", "@example.org", "@example.net"))
    )


def _usable_legacy_phone(value):
    candidate = (value or "").strip()
    digits = "".join(character for character in candidate if character.isdigit())
    return (
        candidate
        and "x" not in candidate.lower()
        and 7 <= len(digits) <= 15
        and digits not in PLACEHOLDER_PHONE_DIGITS
    )


def bridge_legacy_contact(apps, schema_editor):
    SiteConfiguration = apps.get_model("home", "Main_things")
    configuration = SiteConfiguration.objects.order_by("-pk").first()
    if not configuration:
        return
    updates = {"singleton_key": 1}
    if not configuration.primary_email and _usable_legacy_email(configuration.email):
        updates["primary_email"] = configuration.email.strip()
    if not configuration.primary_phone and _usable_legacy_phone(configuration.noumber):
        updates["primary_phone"] = configuration.noumber.strip()
    SiteConfiguration.objects.filter(pk=configuration.pk).update(**updates)


def restore_legacy_contact(apps, schema_editor):
    SiteConfiguration = apps.get_model("home", "Main_things")
    configuration = SiteConfiguration.objects.filter(singleton_key=1).first()
    if not configuration:
        return
    updates = {"singleton_key": None}
    if not configuration.email and configuration.primary_email:
        updates["email"] = configuration.primary_email
    if not configuration.noumber and configuration.primary_phone:
        updates["noumber"] = configuration.primary_phone
    SiteConfiguration.objects.filter(pk=configuration.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_triprequest_trippreference_routeproposal_entryplan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main_things',
            options={'permissions': (('manage_site_configuration', 'Can manage site and brand configuration'),), 'verbose_name': 'Site and brand configuration', 'verbose_name_plural': 'Site and brand configuration'},
        ),
        migrations.AddField(
            model_name='main_things',
            name='active_public_languages',
            field=models.JSONField(default=home.models.default_public_languages),
        ),
        migrations.AddField(
            model_name='main_things',
            name='booking_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='main_things',
            name='business_hours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='canonical_scheme',
            field=models.CharField(choices=[('https', 'HTTPS'), ('http', 'HTTP')], default='https', max_length=5),
        ),
        migrations.AddField(
            model_name='main_things',
            name='dari_brand_name',
            field=models.CharField(default='لارموند تراول و تور', max_length=160),
        ),
        migrations.AddField(
            model_name='main_things',
            name='default_currency',
            field=models.CharField(choices=[('USD', 'USD'), ('AFN', 'AFN'), ('EUR', 'EUR')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='main_things',
            name='default_social_image',
            field=models.FileField(blank=True, upload_to='brand/social/', validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='emergency_operations_phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[home.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='enquiry_response_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='favicon',
            field=models.FileField(blank=True, upload_to='brand/icons/', validators=[django.core.validators.FileExtensionValidator(('ico', 'svg', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='hero_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='hero_heading',
            field=models.CharField(default='Afghanistan, hosted by those who call it home.', max_length=255),
        ),
        migrations.AddField(
            model_name='main_things',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='legacy_domain',
            field=models.CharField(blank=True, default='afghanawaits.com', max_length=253, validators=[home.validators.validate_domain_name]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='legal_entity_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='main_things',
            name='licence_authority',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='main_things',
            name='licence_document',
            field=models.FileField(blank=True, upload_to='brand/licence/', validators=[django.core.validators.FileExtensionValidator(('pdf', 'jpg', 'jpeg', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='licence_number',
            field=models.CharField(blank=True, default='', max_length=100, validators=[home.validators.validate_licence_number]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='logo_monochrome',
            field=models.FileField(blank=True, upload_to='brand/logos/', validators=[django.core.validators.FileExtensionValidator(('svg', 'webp', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='logo_primary',
            field=models.FileField(blank=True, upload_to='brand/logos/', validators=[django.core.validators.FileExtensionValidator(('svg', 'webp', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='logo_reversed',
            field=models.FileField(blank=True, upload_to='brand/logos/', validators=[django.core.validators.FileExtensionValidator(('svg', 'webp', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='logo_symbol',
            field=models.FileField(blank=True, upload_to='brand/icons/', validators=[django.core.validators.FileExtensionValidator(('svg', 'webp', 'png')), home.validators.validate_brand_asset_size]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='office_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='office_city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='main_things',
            name='office_country',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='main_things',
            name='official_brand_name',
            field=models.CharField(default='Larmoond Travel and Tours', max_length=160),
        ),
        migrations.AddField(
            model_name='main_things',
            name='operating_company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='main_things',
            name='primary_domain',
            field=models.CharField(blank=True, default='', max_length=253, validators=[home.validators.validate_domain_name]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='primary_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='main_things',
            name='primary_phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[home.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='primary_tagline',
            field=models.CharField(default='Your Local Host in Afghanistan', max_length=200),
        ),
        migrations.AddField(
            model_name='main_things',
            name='safety_notice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='secondary_phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[home.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='short_brand_name',
            field=models.CharField(default='Larmoond Travel', max_length=100),
        ),
        migrations.AddField(
            model_name='main_things',
            name='show_fixed_departures',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_things',
            name='show_licence_badge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_things',
            name='show_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_things',
            name='show_team_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='main_things',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='main_things',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='main_things',
            name='tripadvisor_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='main_things',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', max_length=30, validators=[home.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='main_things',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='main_things',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='main_things',
            name='noumber',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RunPython(bridge_legacy_contact, restore_legacy_contact),
    ]
